language: node_js
node_js:
    - '8'
    - '7'
notifications:
    slack:
        rooms:
            - <account>:<notice_token>#overlookingbot-dev
        on_success: always
        on_failure: always
        on_cancel: always
