language: node_js
node_js:
    - '8'
    - '7'
notifications:
    webhooks:
        urls:
            - https://script.google.com/macros/s/AKfycbx7-PiGCpVKqVIELqhmDbrk_ADB8Gl861zSnDYRcczZdZy2A5k/exec
        on_success: always
        on_failure: always
        on_cancel: always
