language: node_js
node_js:
    - '7'
cache: npm
notifications:
    slack:
        rooms:
            - overlooking6083:abUaxczoJQfFcRW72EsYbePe#overlookingbot-dev
        on_success: always
        on_failure: always
        on_cancel: always
