version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7
    working_directory: ~/repo

    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: eslint check
          command: npm run lint
      - run: # run tests
          name: test
          command: npm test
      - run:
          name: upload coverage
          command: npm run report-coverage
      - store_artifacts: # special step to save test results as as artifact
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results: # special step to upload test results for display in Test Summary
          path: test-results.xml
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
