version: 2
references:
  container_config: &container_config
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
  workspace_root: &workspace_root
    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root
  npm_cache_key: &npm_cache_key
    dependency-cache-{{ checksum "package.json" }}
  npm_backup_cache_key: &npm_backup_cache_key
    dependency-cache

  restore_node_modules: &restore_node_modules
    restore_cache:
      keys:
        - *npm_cache_key
        - *npm_backup_cache_key
  restore_repo: &restore_repo
    restore_cache:
      keys:
        - v1-repo-{{ .Branch }}-{{ .Revision }}
        - v1-repo-{{ .Branch }}
        - v1-repo
jobs:
  setup_env:
    <<: *container_config
    steps:
      - checkout
      - *restore_node_modules
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@6.4.1'
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: *npm_cache_key
          paths:
            - ./node_modules
      - save_cache:
          key: v1-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - .
  build:
    <<: *container_config
    steps: # a collection of executable commands
      - *attach_workspace
      - *restore_repo
      - *restore_node_modules
      - run:
          name: eslint check
          command: npm run lint
      - run:
          name: test
          command: npm test
      - run:
          name: upload coverage
          command: npm run report-coverage
      - store_artifacts: # special step to save test results as as artifact
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results: # special step to upload test results for display in Test Summary
          path: test-results.xml
  deploy:
    <<: *container_config
    steps:
      - *attach_workspace
      - *restore_repo
      - *restore_node_modules

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - setup_env
      - build:
          requires:
          - setup_env
      - deploy:
          requires:
          - build
          filters:
            branches:
              only: master
